[Colors]
# Color: RGBA hexadecimal integer
iText = 0xFFFFFFFF
iTextDisabled = 0x7F7F7FFF
iWindowBg = 0x000000AD
iChildBg = 0x000000AD
iPopupBg = 0x000000AD
iBorder = 0x0
iBorderShadow = 0x0
iFrameBg = 0x000000AD
iFrameBgHovered = 0x000000AD
iFrameBgActive = 0x000000AD
iTitleBg = 0x000000AD
iTitleBgActive = 0x000000AD
iTitleBgCollapsed = 0x000000AD
iMenuBarBg = 0x0
iScrollbarBg = 0x7F7F7F7F
iScrollbarGrab = 0xDFDFDF7F
iScrollbarGrabHovered = 0xDFDFDFFF
iScrollbarGrabActive = 0xDFDFDFFF
iCheckMark = 0xFFFFFFFF
iSliderGrab = 0xDFDFDF7F
iSliderGrabActive = 0xDFDFDFFF
iButton = 0x0
iButtonHovered = 0x7F7F7FFF
iButtonActive = 0x7F7F7FFF
iHeader = 0x0
iHeaderHovered = 0x0
iHeaderActive = 0x0
iSeparator = 0x7F7F7FFF
iSeparatorHovered = 0x7F7F7FFF
iSeparatorActive = 0x7F7F7FFF
iResizeGrip = 0x0
iResizeGripHovered = 0x0
iResizeGripActive = 0x0
iTab = 0x0
iTabHovered = 0x0
iTabActive = 0x0
iTabUnfocused = 0x0
iTabUnfocusedActive = 0x0
iPlotLines = 0x0
iPlotLinesHovered = 0x0
iPlotHistogram = 0x0
iPlotHistogramHovered = 0x0
iTableHeaderBg = 0x0
iTableBorderStrong = 0xFFFFFFFF
iTableBorderLight = 0xFFFFFFFF
iTableRowBg = 0x0
iTableRowBgAlt = 0x0
iTextSelectedBg = 0x0
iDragDropTarget = 0x0
iNavHighlight = 0xDFDFDFFF
iNavWindowingHighlight = 0xDFDFDFFF
iNavWindowingDimBg = 0x7F7F7FBF
iModalWindowDimBg = 0x7F7F7FBF
