# For hotkey code reference, see:
# https://wiki.nexusmods.com/index.php/DirectX_Scancodes_And_How_To_Use_Them
# https://ck.uesp.net/wiki/Input_Script
#
# To disable a hotkey, set iHotkeyXXX and iModifierXXX to 0.
# To disable a modifier, set iModifierXXX to 0.

# Toggle UI hotkey.
#
# Default: 59 (F1)
iHotkey = 59
# Default: 0 (Disabled)
iModifier = 0
