[General]
# The language used in this mod. If not specified, use game language.
#sLanguage = "chinese"
# The file path of font used in this mod.
sFont = "Data/Interface/ImGuiResources/Fonts/LXGWWenKaiMono-Regular.ttf"

[Controls]
# For hotkey code reference, see:
# https://wiki.nexusmods.com/index.php/DirectX_Scancodes_And_How_To_Use_Them
# https://ck.uesp.net/wiki/Input_Script
#
# To disable a hotkey, set iHotkey and iModifier to 0.
# To disable a modifier, set iModifier to 0.

[Controls.Keyboard]
# Toggle menu hotkey.
#
# Default: 59 (F1)
iHotkey = 59
# Default: 0 (Disabled)
iModifier = 0

# Exit menu extra hotkey.
#
# Default: 1 (Esc)
iExtraExit = 1

[Controls.Gamepad]
# Toggle menu hotkey.
#
# Default: 0 (Disabled)
iHotkey = 0
# Default: 0 (Disabled)
iModifier = 0

# Exit menu extra hotkey.
#
# Default: 0 (Disabled)
iExtraExit = 0
