set(headers
    src/CLib/Hook.h
    src/CLib/Key.h
    src/Configuration.h
    src/Core.h
    src/Function.h
    src/Hooks.h
    src/HotkeyManager.h
    src/ImGui/Input.h
    src/ImGui/Menu.h
    src/ImGui/Renderer.h
    src/InputManager.h
    src/PCH.h
    src/Translation.h
    src/Util/Singleton.h
    src/Util/TOML.h
    src/Util/Win.h
    vendor/backends/imgui_impl_dx11.h
    vendor/backends/imgui_impl_win32.h
    vendor/imconfig.h
    vendor/imconfig_user.h
    vendor/imgui.h
    vendor/imgui_internal.h
    vendor/imstb_rectpack.h
    vendor/imstb_textedit.h
    vendor/imstb_truetype.h
    vendor/misc/freetype/imgui_freetype.h
)
